apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: randomy
  name: randomy
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: randomy
    spec:
      containers:
      - args:
        - npm
        - start
        image: juananantona/randomy
        name: randomy
        ports:
        - containerPort: 3000
        resources: {}
      restartPolicy: Always
status: {}
